### ISSUE TITLE
Weird error

### ISSUE THREAD

**Issue by maxyboiii** [cgisca/PGSGP#1] opened 2020-02-01 17:54 UTC
this guy and me have the same problem:
https://godotengine.org/qa/52856/android-plugin-using-play-services-nearby

**Comment by himaghnam** [comment] 2020-02-08 05:47
I added these lines in gradle.properties in build folder and it is working for me now
``` 
android.useAndroidX=true
android.enableJetifier=true
```

**Comment by BThacker** [comment] 2020-02-12 02:51
I had a similar issue caused by duplicate code. Adding the:
android.useAndroidX=true
android.enableJetifier=true

to gradle.properties seems to have resolved it for me as well, will do further testing soon

**Comment by cgisca** [comment] 2020-04-08 17:23
Closing this issue as it seems to be fixed by adding  to `gradle.properties`
`
android.useAndroidX=true
android.enableJetifier=true
`

**Closed as completed by cgisca** 2020-04-08 17:23 UTC
